### ISSUE TITLE
 Exception on the OpenGL thread

### ISSUE THREAD

**Issue by jrse** [SJ-Wolf/Tensorflow-ARCore#2]
07-17 15:49:35.031 12737-12771/org.tensorflow.demo E/HelloArActivity: Exception on the OpenGL thread
    java.lang.IllegalAccessError: Method 'android.graphics.Bitmap android.graphics.Bitmap.createBitmap(int, int, android.graphics.Bitmap$Config, boolean)' is inaccessible to class 'org.tensorflow.demo.HelloArActivity' (declaration of 'org.tensorflow.demo.HelloArActivity' appears in /data/app/org.tensorflow.demo-1/split_lib_slice_7_apk.apk)
        at org.tensorflow.demo.HelloArActivity.renderProcessedImageGpuDownload(HelloArActivity.java:565)
        at org.tensorflow.demo.HelloArActivity.onDrawFrame(HelloArActivity.java:508)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
07-17 15:49:36.783 12737-12908/org.tensorflow.demo E/native: camera_image_stream.cc:114 Faile

**Comment by jrse** [comment]
i see it has something to do with my minsdk setting. the fork of @jettyz works pretty good on my device.
